[package]
name = "cve-2018-16763"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.19"
tokio = { version = "1.15.0", features = ["full"] }
reqwest = { version= "0.11.9", features =["cookies"]}
anyhow = "1.0.53"
url = "2.2.2"
